baseurl = "http://tracknut.ca/"
languageCode = "en-ca"
title = "Track Nut"
paginate = 5
DisqusShortname = "tracknutca"
Copyright = "All rights reserved - 2016"
canonifyurls = false
theme = "casper"

[blackfriday]
  hrefTargetBlank = true

# Grid-Side theme configuration
SectionPagesMenu = "Main"

[params]
  description = "Rekindling the passion for track cycling"
  author = "no-author"
  #authorlocation = "Ottawa, Ontario, Canada"
  #authorwebsite = "http://vjeantet.fr"
  #bio= "note about me"
  cover = "graphics/Track-Cover-Photo.jpg"
  headerimage = "graphics/FCV-Header-Photo.jpg"  #Used in list pages of sections
  #logo = "graphics/cycling-logo-blue-red.png"
  bottomlogo = "graphics/bicycle-round-black-notext-280x280.png"
  listlogo = "graphics/bicycle-round-black-notext-280x280.png"
  #googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xm
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "abbourne"
  twitterName = "abbourne"
  facebookName = "abbourne"
  #linkedinName = "http://ca.linkedin.com/in/williambourne/"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  sidebarHeader = "Sidebar Header"
  sidebarText = "Here's a [link to google](https://www.google.com)"
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Sidebar Links"
  github = "https://github.com/parsiya/"
  bitbucket = "https://bitbucket.org/parsiya/"
  twitter = "https://twitter.com/cryptogangsta/"
  keybase = "https://keybase.io/parsiya/"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "Home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 20
  identifier = "About"
  url = "/about"

[[menu.main]]
  name = "Posts"
  weight = 25
  identifier = "Posts"
  url = "/post"

[[menu.main]]
  name = "The Rules"
  weight = 30
  identifier = "The Rules"
  url = "/rules"

[[menu.main]]
  name = "Track Resources"
  weight = 40
  identifier = "Track Resources"
  description = "Lots of interesting stuff"
  url = "/resources"



